### ISSUE TITLE
Build broken by commit fc2e543

### ISSUE THREAD

**Issue by aklein3** [lattice-land/lala-core#6]
@ptal, it looks like commit https://github.com/lattice-land/lala-core/commit/fc2e543aec4db9289c088045aa66791e664eada7 broke the build on main.

![broke_build](https://github.com/lattice-land/lala-core/assets/155021931/2b821054-9765-4f7d-912d-a60ce21131d9)

**Comment by ptal** [comment]
Actually, I'm using main as a `dev` branch. Sometimes it doesn't compile because I push code between my two computers, and since I'm working alone, it's not a big issue so far. If you want a stable version, you should use the tagged version such as `v1.1.0`. I'm going to fix it today anyways.

**Comment by ptal** [comment]
Fixed :-)

**Comment by aklein3** [comment]
Thank you!

On the small teams I've worked on, we typically each have a personal dev branch that is not pushed (except perhaps to copy it to another PC like you do).  When we have something working and ready to show to the others, we merge our dev branch and push it to main, with the caveat that it might be unstable or have issues.  When ready, the maintainer eventually tags a release. 

But hey, it's your project, your rules, so it's cool.  Thanks for the info.
